### ISSUE TITLE
[feature request] Support OpenWlanMap database

### ISSUE THREAD

**Issue by twzkxkan** [n76/wifi_backend#18] opened 2015-11-23 20:49 UTC
Similar to your [GSM Location Provider](https://github.com/n76/Local-GSM-Backend), support downloading and use of external databases for offline use. Is this practical?

**Comment by n76** [comment] 2015-11-23 21:00
I am not sure what you mean when you mention "offline use". This WiFi backend is designed to work off line and does not access the network at all. I am almost always running with data turned off. For my use case where I use a navigation app to get to most places the backend has properly learned the WiFi APs along the way and gets me a quick position fix when I fire up the nav app later.

I think this might fall under the same umbrella as issue 17 at https://github.com/n76/wifi_backend/issues/17

If issue 17 is implemented, a generic comma separated value file would be used for the export and import. A few easy scripts should allow one to use pretty nearly any external WiFi AP provider's data.

I am going to close this as a near duplicate of issue 17 as the functionality desired should be possible with a good implementation of that issue.

**Closed by n76** 2015-11-23 21:00 UTC
