### ISSUE TITLE
High battery consumption even though location is disabled

### ISSUE THREAD

**Issue by aelmahmoudy** [n76/wifi_backend#1] opened 2014-12-20 10:23 UTC
Battery stats show that Local WiFi backend is second in power consumption after the screen (~20%), although I had the location disabled on the phone.
I am using OMNI Kitkat 4.4.4

**Comment by n76** [comment] 2015-02-10 17:07
Closing as no logcat given and I can't reproduce on my phone.

**Closed by n76** 2015-02-10 17:07 UTC
