### ISSUE TITLE
APs from connected SSID not used?

### ISSUE THREAD

**Issue by gdt** [n76/wifi_backend#40] opened 2016-08-30 23:40 UTC
I am not really sure I am describing this precisely and correctly, but it seems that access points from the currently connected SSID are not used.  Or maybe no access points are used when connected.   I am often in a place with a handful of APs on one SSID, and no other APs in range.  Here, I get no location.   If I move several hundred meters and pick up an AP from a network that I don't associate with, it works.   Or it works with the APs I use as I approach.   Again, take details with a grain of salt.

I wonder if no one else notices because the idea of not picking up foreign APs just doesn't happen in the city.

Yes, I know I should run adb.

**Comment by n76** [comment] 2016-08-31 00:09
Using adb logcat might help. :)

But it is also possible that the cause of your problem is not properly logged. :(

The problem with determining position based on observed WiFi/WLAN APs is that they can move without warning. The backend attempts to deal with this in several ways:

1. If the SSID is or contains a value that indicates that they might be installed in a vehicle or that the owner does not want them mapped. See the [blacklist file in the source code](https://github.com/n76/wifi_backend/blob/master/app/src/main/java/org/fitchfamily/android/wifi_backend/wifi/WifiBlacklist.java) for current values. This is the only use of the SSID, all other processing is done based on BSSID (i.e. MAC address).
2. If we observe a signal an implausible distance from the previous location we mark the AP as not to be used for location calculations until we get enough more observations confirming it is now stationary at the new location.
3. When actually trying to determine a location we group the observed APs that we have a stable location for based on distance from one another and then we take the largest group.
4. Finally, we require the largest group to have a minimum of two APs. (I suspect this is your problem.)

So far, I've not seen a false location based on a moved or moving APs though there are obvious cases where it may fail. For example, a cruise ship with multiple APs observable just leaving port. Though with a locked GPS all the APs on board ought to be tagged as moved and suspect before the ship gets too far.

So some questions:

1. Are all those APs in your problem location sharing the same BSSID (I've heard of some corporate networks that do that). That would make it appear that there is only one AP in the area and it may have an implausibly large coverage area.
2. Are those APs spread apart such that you only have one observable at any given time?
3. Can you get a logcat?
4. If the released backend does not have sufficient logging, would you mind running a debug version with more logging for me? (It would have a different signature, so your current database will be lost and you will have to export it before installing one from me then import the data back).

**Comment by gdt** [comment] 2016-08-31 00:16
There are two APs.  One is 2.4/5, and one is just 2.4.  They are normal devices that shouldn't be blacklisted and they have not moved (well, I moved one 10m within the house).    They are not that far apart, and I almost always see both of the 2.4.

I'll work on logcat, and then I'll switch to a local build instead of f-droid, and then I can try changes in branches, or add my own logging.  I'll also look for the APs in the export.

Other than this one situation the backend works great, and I have 45469 APs observed, which is a side effect of using osmand and thus having the GPS on a lot.

**Comment by n76** [comment] 2016-08-31 00:23
Sounds like you know what you are doing.

It may take a little while to import those 45K APs as the current export generates a record for each of the up to three saved observations. And the import does a merge with what ever is in the phone using the same logic as if the AP was just reported by the operating system.

When you find the issue, I will work with your to get what ever code modifications are needed into this repository.

**Comment by n76** [comment] 2017-03-02 00:04
No new information. Assume issue is due to local conditions and am closing it.

**Closed by n76** 2017-03-02 00:04 UTC
